=== zhigimont-k/Epam_Task_XML_Web_Parsing/src/main/resources/data/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://myNameSpace.com"
           xmlns="http://myNameSpace.com"
           elementFormDefault="qualified">
    <xs:element name="papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="paper" minOccurs="2" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="paper" type="Paper" abstract="true"/>
    <xs:element name="newspaper" type="Newspaper" substitutionGroup="paper"/>
    <xs:element name="magazine" type="Magazine" substitutionGroup="paper"/>
    <xs:element name="booklet" type="Booklet" substitutionGroup="paper"/>

    <xs:complexType name="Paper">
        <xs:sequence>
            <xs:element name="monthly" type="xs:boolean" default="true"/>
            <xs:element name="color" type="xs:boolean" default="false"/>
            <xs:element name="volume" type="xs:positiveInteger"/>
            <xs:element name="first-publication" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="title" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Newspaper">
        <xs:complexContent>
            <xs:extension base="Paper">
                <xs:sequence>
                    <xs:element name="subscription-index" type="subscription-index" default="00000000"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Magazine">
        <xs:complexContent>
            <xs:extension base="Paper">
                <xs:sequence>
                    <xs:element name="gloss" type="xs:boolean" default="true"/>
                    <xs:element name="subscription-index" type="subscription-index" default="00000000"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Booklet">
        <xs:complexContent>
            <xs:extension base="Paper">
                <xs:sequence>
                    <xs:element name="gloss" type="xs:boolean" default="true"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="subscription-index">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{6,8}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== zhigimont-k/Epam_Task_XML_Web_Parsing/src/main/resources/data/papers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<papers xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://myNameSpace.com"
        xs:schemaLocation="http://www.example.com/papers.xsd">
    <newspaper id="1" title="Weekly Newspaper">
        <monthly>false</monthly>
        <color>true</color>
        <volume>200</volume>
        <first-publication>1970-12-12</first-publication>
        <subscription-index>12445800</subscription-index>
    </newspaper>

    <newspaper id="2" title="Monthly Newspaper">
        <monthly>true</monthly>
        <color>false</color>
        <volume>42</volume>
        <first-publication>2000-04-02</first-publication>
        <subscription-index>27866512</subscription-index>
    </newspaper>

    <magazine id="3" title="Some magazine">
        <monthly>true</monthly>
        <color>true</color>
        <volume>300</volume>
        <first-publication>2015-08-04</first-publication>
        <gloss>true</gloss>
        <subscription-index>65827465</subscription-index>
    </magazine>

    <magazine id="4" title="Some other magazine">
        <monthly>false</monthly>
        <color>true</color>
        <volume>60</volume>
        <first-publication>2008-01-11</first-publication>
        <gloss>false</gloss>
        <subscription-index>76683550</subscription-index>
    </magazine>

    <magazine id="5" title="Elle">
        <monthly>false</monthly>
        <color>true</color>
        <volume>120</volume>
        <first-publication>1999-11-09</first-publication>
        <gloss>true</gloss>
        <subscription-index>65588476</subscription-index>
    </magazine>

    <magazine id="6" title="Il">
        <monthly>true</monthly>
        <color>true</color>
        <volume>185</volume>
        <first-publication>1995-02-10</first-publication>
        <gloss>true</gloss>
        <subscription-index>23315065</subscription-index>
    </magazine>

    <booklet id="7" title="Gastrofest booklet">
        <monthly>false</monthly>
        <color>true</color>
        <volume>2</volume>
        <first-publication>2017-08-07</first-publication>
        <gloss>false</gloss>
    </booklet>

    <booklet id="8" title="OSTIS booklet">
        <monthly>false</monthly>
        <color>true</color>
        <volume>5</volume>
        <first-publication>2011-02-17</first-publication>
        <gloss>false</gloss>
    </booklet>

    <booklet id="9" title="BSUIR booklet">
        <monthly>false</monthly>
        <color>true</color>
        <volume>3</volume>
        <first-publication>2015-08-31</first-publication>
        <gloss>false</gloss>
    </booklet>

    <magazine id="10" title="Yet another magazine">
        <monthly>true</monthly>
        <color>true</color>
        <volume>40</volume>
        <first-publication>2013-03-14</first-publication>
        <gloss>true</gloss>
        <subscription-index>56648803</subscription-index>
    </magazine>

    <magazine id="11" title="We need more magazines">
        <monthly>false</monthly>
        <color>true</color>
        <volume>58</volume>
        <first-publication>2013-10-15</first-publication>
        <gloss>true</gloss>
        <subscription-index>11938803</subscription-index>
    </magazine>

    <magazine id="12" title="Another magazine">
        <monthly>false</monthly>
        <color>true</color>
        <volume>66</volume>
        <first-publication>2003-01-12</first-publication>
        <gloss>true</gloss>
        <subscription-index>00198597</subscription-index>
    </magazine>

    <newspaper id="13" title="Some newspaper">
        <monthly>false</monthly>
        <color>true</color>
        <volume>66</volume>
        <first-publication>2007-11-20</first-publication>
        <subscription-index>10097594</subscription-index>
    </newspaper>

    <newspaper id="14" title="Another newspaper">
        <monthly>false</monthly>
        <color>false</color>
        <volume>24</volume>
        <first-publication>2012-12-21</first-publication>
        <subscription-index>21775649</subscription-index>
    </newspaper>

    <newspaper id="15" title="Newspaper Number N">
        <monthly>false</monthly>
        <color>false</color>
        <volume>19</volume>
        <first-publication>2011-05-29</first-publication>
        <subscription-index>44726539</subscription-index>
    </newspaper>

    <newspaper id="16" title="Newspaper Number N+1">
        <monthly>false</monthly>
        <color>false</color>
        <volume>21</volume>
        <first-publication>1997-11-02</first-publication>
        <subscription-index>32336284</subscription-index>
    </newspaper>
</papers>

=== zhigimont-k/Epam_Task_XML_Web_Parsing/data/papers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:xs="http://www.example.com/students"
           xsi:schemaLocation="http://www.example.com/papers.xsd">
    <xs:newspaper id="1" name="Weekly Newspaper">
        <xs:monthly>false</xs:monthly>
        <xs:color>false</xs:color>
        <xs:volume>200</xs:volume>
        <xs:subscription-index>12445800</xs:subscription-index>
        <xs:first-publication>1970-12-12</xs:first-publication>
    </xs:newspaper>

    <xs:newspaper id="2" name="Monthly Newspaper">
        <xs:monthly>true</xs:monthly>
        <xs:color>false</xs:color>
        <xs:volume>42</xs:volume>
        <xs:subscription-index>278665123</xs:subscription-index>
        <xs:first-publication>2000-04-02</xs:first-publication>
    </xs:newspaper>

    <xs:magazine id="3" name="Some magazine">
        <xs:monthly>true</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>300</xs:volume>
        <xs:subscription-index>65827465</xs:subscription-index>
        <xs:first-publication>2015-08-04</xs:first-publication>
    </xs:magazine>

    <xs:magazine id="4" name="Some other magazine">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>false</xs:glossy>
        <xs:volume>60</xs:volume>
        <xs:subscription-index>76683550</xs:subscription-index>
        <xs:first-publication>2008-01-11</xs:first-publication>
    </xs:magazine>

    <xs:magazine id="5" name="Elle">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>120</xs:volume>
        <xs:subscription-index>65588476</xs:subscription-index>
        <xs:first-publication>1999-11-09</xs:first-publication>
    </xs:magazine>

    <xs:magazine id="6" name="Il">
        <xs:monthly>true</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>185</xs:volume>
        <xs:subscription-index>23315065</xs:subscription-index>
        <xs:first-publication>1995-02-10</xs:first-publication>
    </xs:magazine>

    <xs:booklet id="7" name="Gastrofest booklet">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>false</xs:glossy>
        <xs:volume>2</xs:volume>
        <xs:first-publication>2017-08-07</xs:first-publication>
    </xs:booklet>

    <xs:booklet id="8" name="OSTIS booklet">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>false</xs:glossy>
        <xs:volume>5</xs:volume>
        <xs:first-publication>2011-02-17</xs:first-publication>
    </xs:booklet>

    <xs:booklet id="9" name="BSUIR booklet">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>false</xs:glossy>
        <xs:volume>3</xs:volume>
        <xs:first-publication>2015-08-31</xs:first-publication>
    </xs:booklet>

    <xs:magazine id="10" name="Yet another magazine">
        <xs:monthly>true</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>40</xs:volume>
        <xs:subscription-index>56648803</xs:subscription-index>
        <xs:first-publication>2013-03-14</xs:first-publication>
    </xs:magazine>

    <xs:magazine id="11" name="We need more magazines">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>58</xs:volume>
        <xs:subscription-index>11938803</xs:subscription-index>
        <xs:first-publication>2013-10-15</xs:first-publication>
    </xs:magazine>

    <xs:magazine id="12" name="Another magazine">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:glossy>true</xs:glossy>
        <xs:volume>66</xs:volume>
        <xs:subscription-index>00198597</xs:subscription-index>
        <xs:first-publication>01-12-2003</xs:first-publication>
    </xs:magazine>

    <xs:newspaper id="13" name="Some newspaper">
        <xs:monthly>false</xs:monthly>
        <xs:color>true</xs:color>
        <xs:volume>66</xs:volume>
        <xs:subscription-index>10097594</xs:subscription-index>
        <xs:first-publication>20-11-2007</xs:first-publication>
    </xs:newspaper>

    <xs:newspaper id="14" name="Another newspaper">
        <xs:monthly>false</xs:monthly>
        <xs:color>false</xs:color>
        <xs:volume>24</xs:volume>
        <xs:subscription-index>21775649</xs:subscription-index>
        <xs:first-publication>21-12-2012</xs:first-publication>
    </xs:newspaper>

    <xs:newspaper id="15" name="Newspaper Number N">
        <xs:monthly>false</xs:monthly>
        <xs:color>false</xs:color>
        <xs:volume>19</xs:volume>
        <xs:subscription-index>44726539</xs:subscription-index>
        <xs:first-publication>29-05-2011</xs:first-publication>
    </xs:newspaper>

    <xs:newspaper id="16" name="Newspaper Number N+1">
        <xs:monthly>false</xs:monthly>
        <xs:color>false</xs:color>
        <xs:volume>21</xs:volume>
        <xs:subscription-index>32336284</xs:subscription-index>
        <xs:first-publication>11-02-1997</xs:first-publication>
    </xs:newspaper>
</xs:papers>
