=== zhigimont-k/Epam_Task_XML_Web_Parsing/data/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.example.com/papers"
           xmlns:tns="https://www.example.com/papers"
           elementFormDefault="qualified">
    <xs:element name="papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:paper" minOccurs="2" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="paper" type="tns:Paper" abstract="true"/>
    <xs:element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:paper"/>
    <xs:element name="magazine" type="tns:Magazine" substitutionGroup="tns:paper"/>
    <xs:element name="booklet" type="tns:Booklet" substitutionGroup="tns:paper"/>

    <xs:complexType name="Paper">
        <xs:sequence>
            <xs:element name="color" type="xs:boolean" default="false"/>
            <xs:element name="monthly" type="xs:boolean" default="true"/>
            <xs:element name="volume" type="xs:positiveInteger"/>
            <xs:element name="first-publication" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Newspaper">
        <xs:complexContent>
            <xs:extension base="tns:Paper">
                <xs:all>
                    <xs:element name="post-index" type="tns:post-index" default="000000"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Magazine">
        <xs:complexContent>
            <xs:extension base="tns:Paper">
                <xs:all>
                    <xs:element name="gloss" type="xs:boolean" default="true"/>
                    <xs:element name="post-index" type="tns:post-index" default="000000"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Booklet">
        <xs:complexContent>
            <xs:extension base="tns:Paper">
                <xs:all>
                    <xs:element name="gloss" type="xs:boolean" default="true"/>
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="post-index">
        <xs:restriction base="xs:positiveInteger">
            <xs:length value="8"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== zhigimont-k/Epam_Task_XML_Web_Parsing/data/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:Test.titlespace"
        xsi:schemaLocation="http://www.example.com/papers.xsd">
    <newspaper id="1" title="Weekly Newspaper">
        <monthly>false</monthly>
        <color>true</color>
        <volume>200</volume>
        <subscription-index>12445800</subscription-index>
        <first-publication>1970-12-12</first-publication>
    </newspaper>
	
    <magazine id="2" title="Some magazine">
        <monthly>true</monthly>
        <color>true</color>
        <gloss>true</gloss>
        <volume>300</volume>
        <subscription-index>65827465</subscription-index>
        <first-publication>2015-08-04</first-publication>
    </magazine>
	
    <booklet id="3" title="OSTIS booklet">
        <monthly>false</monthly>
        <color>true</color>
        <volume>5</volume>
        <gloss>false</gloss>
        <first-publication>2011-02-17</first-publication>
    </booklet>
</papers>
